Revert to runnable PostgreSQL, fails on rtpostgis
Says missing, but present on disk.

```
ERROR:  could not load library "/pgsql/lib/rtpostgis-2.5.dll":
        The specified module could not be found.
```